CREATE TABLE patient (
                         patient_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         first_name VARCHAR2(100) NOT NULL,
                         last_name VARCHAR2(100) NOT NULL,
                         date_of_birth DATE NOT NULL,
                         gender VARCHAR2(20) NOT NULL,
                         phone VARCHAR2(20),
                         email VARCHAR2(150) UNIQUE,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT chk_patient_gender
                             CHECK (gender IN ('MALE', 'FEMALE', 'OTHER'))
);

CREATE TABLE encounter (
                           encounter_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           patient_id NUMBER(19) NOT NULL,
                           encounter_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           encounter_type VARCHAR2(50) NOT NULL,
                           diagnosis VARCHAR2(500),
                           status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
                           notes VARCHAR2(1000),
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                           CONSTRAINT fk_encounter_patient
                               FOREIGN KEY (patient_id)
                                   REFERENCES patient(patient_id),

                           CONSTRAINT chk_encounter_status
                               CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED'))
);

CREATE INDEX idx_encounter_patient
    ON encounter(patient_id);